ENH Allow creating temporary templates
silverstripe-labs/silverstripe-behat-extension pull request #214
Opened 2022-04-27 01:07 UTC by GuySartorelli

Required for silverstripe/silverstripe-elemental#980

Provides a way to safely add a temporary template for a given scenario, which gets cleaned up afterwards (consistent with the way temporary config is added)

2022-04-27 04:01 UTC, emteknetnz requested changes
I'd question why we even need to have mock templates when we're testing the "out of the box" experience

Wouldn't a better solution be to just add an actual template to admin or similar module?

2022-04-27 04:01 UTC, emteknetnz commented on src/Context/FixtureContext.php
> +
```suggestion
```
I'm not a fan of extra lines line this, it's still easy to read without them and it just increases the need for scrolling

2022-04-27 04:01 UTC, emteknetnz commented on src/Context/FixtureContext.php
> +        $project = ModuleManifest::config()->get('project') ?: 'mysite';
```suggestion
        $project = ModuleManifest::config()->get('project') ?: 'app';
```
More likely to be `app` these days?

2022-04-27 04:27 UTC, GuySartorelli commented on src/Context/FixtureContext.php
> +        $project = ModuleManifest::config()->get('project') ?: 'mysite';
This is just copied from `getDestinationConfigFolder()`, which I've refactored it out from. I can change it if you want, but that's the context.

2022-04-27 04:29 UTC, GuySartorelli commented on src/Context/FixtureContext.php
> +
Fair enough. I was copying the style of `clearConfigFiles()` above. Shall I remove the extra line from both? It'd be nice if we had some policy (extended code style rules or something) that tell us when new lines are or are not appropriate - I reviewed a PR with a similar new line added and questioned it and one of the core committers said they prefer them in there so 🤷‍♀️

2022-04-27 07:18 UTC, GuySartorelli commented
> I'd question why we even need to have mock templates when we're testing the "out of the box" experience
> Wouldn't a better solution be to just add an actual template to admin or similar module if there's a missing template?

The thing is we're testing the preview of the front-end here - and really the theme used to include content on the front-end is very much not out of the box. It's not that a template is "missing" per se - it's just that we don't control the front-end to the extend we control the CMS. We do have a couple of themes but the tests shouldn't be dependent on a specific theme being included. So this allows tests to add front-end templates for testing front-end stuff (like, in the case of the PR that spawned this one, elemental blocks).

I can try to do something with frameworktest if you'd prefer - but elemental doesn't currently have frameworktest as a dependency, plus this allows for the temporary addition of what is effectively a test fixture without needing to include additional libraries, so I kinda like this approach - plus it's consistent with the way config is already being added.

2022-04-27 07:19 UTC, GuySartorelli commented on src/Context/FixtureContext.php
> +        $destPath = $app->getResource("templates/{$filename}")->getPath();
There's an argument to be made that this should be creating a new temporary test theme instead - which I'd be open to doing if that's preferred.

2022-04-28 05:10 UTC, GuySartorelli commented
I thought of a much simpler way of handling this for the one test that needed it, so this PR isn't needed now.

2022-04-28 05:10 UTC, closed without merging