ENH New steps to creat groups and members with permissions
silverstripe-labs/silverstripe-behat-extension pull request #223
Opened 2022-09-02 01:08 UTC by sabina-talipova

### Description
- New methods to generate Group `generateGroupWithPermission()` and Members `generateMemeber()` separately
- Updated  `generateMemberWithPermission()`
- New step `iAmLoggedInAsMemeberOfGroup()` - `Given I am logged in as a memeber of "ADMIN" group`

### Parent issue

- https://github.com/silverstripe/silverstripe-behat-extension/issues/220

2022-09-02 01:46 UTC, GuySartorelli requested changes

2022-09-02 01:46 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +        $group = Group::get()->filter('Title', "$permCode group")->first();
```suggestion
    public function iAmLoggedInAsMemeberOfGroup($groupName)
    {
        $group = Group::get()->filter('Title', "$groupName")->first();
```
Remove the necessity to have "group" at the end of the group name.

2022-09-02 01:46 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +        $this->generateMemeber($email, $password, $group, $permCode);
```suggestion
        $this->generateMember($email, $password, $group, $permCode);
```

2022-09-02 01:46 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +        $this->generateMemeber($email, $password, $group, $permCode);
```suggestion
            throw new LogicException("Group $groupName does not exist");
        }

        $email = "{$groupName}@example.org";
        $password = 'Secret!123';
        $this->generateMemeber($email, $password, $group, $groupName);
```

2022-09-02 01:46 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +        return $this->generateMemeber($email, $password, $group, $permCode);
```suggestion
        return $this->generateMember($email, $password, $group, $permCode);
```

2022-09-02 01:46 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +    protected function generateMemeber($email, $password, $group, $permCode)
```suggestion
    protected function generateMemeber($email, $password, $group, $identifier)
```
It's not necessarily a permission code.

2022-09-02 02:08 UTC, GuySartorelli requested changes

2022-09-02 02:08 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +     * @param string $groupName
```suggestion
     * @param string $permCode
```
This is still the permission code.

2022-09-02 02:08 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +            $group->Title = "$permCode";
```suggestion
        $group = Group::get()->filter('Title', "$permCode group")->first();
        if (!$group) {
            $group = Group::create();
            $group->Title = "$permCode group";
```
We don't want to change the behaviour of generateMemberWithPermission() - that can still add "group" to the end of the group name.

2022-09-02 02:20 UTC, GuySartorelli requested changes

2022-09-02 02:20 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +     * @Given /^I am logged in as a memeber of "([^"]*)" group$/
```suggestion
     * Example: Given I am logged in as a member of "ADMIN" group
     *
     * @Given /^I am logged in as a member of "([^"]*)" group$/
```
Sorry, I should have noticed this typo last time.

2022-09-02 02:47 UTC, GuySartorelli approved these changes
Looks good - hold off merging until at least one of the related PRs is ready.

2022-09-06 00:17 UTC, GuySartorelli requested changes

2022-09-06 00:17 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +    public function iAmLoggedInAsMemeberOfGroup($groupName)
```suggestion
     * Example: Given I am logged in as a member of "ADMIN" group
     *
     * @Given /^I am logged in as a member of "([^"]*)" group$/
     * @param string $groupName
     */
    public function iAmLoggedInAsMemberOfGroup($groupName)
```

2022-09-06 00:20 UTC, sabina-talipova commented on src/Context/LoginContext.php
> +    public function iAmLoggedInAsMemeberOfGroup($groupName)
DONE

2022-09-06 00:24 UTC, GuySartorelli approved these changes

2022-09-06 00:34 UTC, merged