FIX Register against MailerInterface::class
silverstripe-labs/silverstripe-behat-extension pull request #225
Opened 2022-09-28 00:52 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10097

Needs to be merged AFTER merging https://github.com/silverstripe/silverstripe-framework/pull/10494

2022-10-18 00:42 UTC, GuySartorelli approved these changes
Merge only when other PRs are ready to avoid breaking CI

2022-10-18 00:42 UTC, GuySartorelli requested changes

2022-10-18 00:42 UTC, GuySartorelli commented on src/Context/EmailContext.php
>  use SilverStripe\Control\Email\Mailer;
```suggestion
```

2022-10-18 22:21 UTC, emteknetnz commented on src/Context/EmailContext.php
>  use SilverStripe\Control\Email\Mailer;
Updated

2022-10-19 01:41 UTC, GuySartorelli approved these changes

2022-10-19 02:52 UTC, merged