correct required type for findEmail() $to
silverstripe-labs/silverstripe-behat-extension pull request #255
Opened 2023-11-09 23:25 UTC by scott-nz

Follows same logic as thereIsAnEmailTitled() which sets the $to param of findEmail() to an empty string

2023-11-09 23:27 UTC, scott-nz commented
another option to this solution could be to set the findEmail $to type declaration to `?string` but I don't have enough context of the module to be sure that would be no unintended consequences

2023-11-13 23:07 UTC, emteknetnz requested changes
Is this actually fixing a bug?  If it's just refactoring for the sake of consistency then I'd say don't merge it in case there are unintended side effects, though in the using of a null argument is causing issues then I'm OK with merging

2023-11-13 23:47 UTC, scott-nz commented
> Is this actually fixing a bug? If it's just refactoring for the sake of consistency then I'd say don't merge it in case there are unintended side effects, though in the using of a null argument is causing issues then I'm OK with merging

This is a bugfix. 
`findEmail()` requires the $to param to be a string
If my behat call is `there should be an email from "scott-nz@email.com"` this will translate into the function as thereIsAnEmailFromTo('', 'from', 'scott-nz@email.com')
then currently $to will be set to null which causes a type error when `findEmail()` is called

2023-11-14 02:28 UTC, emteknetnz requested changes
Please branch-from/target either 4.11 (CMS 4) or 5.0 (CMS 5) - I'm not sure if the CMS 4 version can have blank string passed to it - if it can please target the CMS 4 branch otherwise targer the CMS 5 branch

2023-11-14 02:37 UTC, scott-nz commented
rebased on 5.0 and target branch updated.
4.11 function declaration allows for null https://github.com/silverstripe/silverstripe-behat-extension/blob/6c962ef2945e4eb45bc632e8f8fbaaf87a4954b8/src/Utility/TestMailer.php#L37

2023-11-14 04:11 UTC, emteknetnz approved these changes

2023-11-14 04:14 UTC, merged

2023-11-14 04:15 UTC, emteknetnz commented
Merged code will be auto tagged shortly