MNT Keyboard test steps
silverstripe-labs/silverstripe-behat-extension pull request #263
Opened 2024-02-15 23:42 UTC by sabina-talipova

## Description
Test steps that simulate user interaction with the application via the keyboard.

## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/205

2024-02-15 23:45 UTC, sabina-talipova commented on src/Context/BasicContext.php
> -use Behat\Behat\Definition\Call;
Unrelated refactoring. We don't use this class in the code any more.

2024-02-18 20:29 UTC, emteknetnz requested changes

2024-02-18 20:29 UTC, emteknetnz commented on src/Context/BasicContext.php
> +    public function iPressTheKeyAndConfirmDialog(string $key)
```suggestion
    public function iPressTheKeyAndConfirmTheDialog(string $key)
```

2024-02-18 22:07 UTC, sabina-talipova commented on src/Context/BasicContext.php
> +    public function iPressTheKeyAndConfirmDialog(string $key)
Updated

2024-02-18 22:53 UTC, emteknetnz approved these changes

2024-02-18 22:53 UTC, merged