FIX Don't use the deprecated 'none' encryptor
silverstripe-labs/silverstripe-behat-extension pull request #272
Opened 2024-05-23 22:37 UTC by GuySartorelli

Setting a Member's `PasswordEncryption` to "none" ends up using the deprecated `PasswordEncryptor_None` class.

There's no reason to not use encryption here.

## Issue
- https://github.com/silverstripe/silverstripe-behat-extension/issues/271

2024-05-24 00:54 UTC, emteknetnz requested changes
You'll need to run this one across sink .. there may actually be a reason we don't know about

2024-05-24 01:53 UTC, GuySartorelli commented
Sink seems excessive, I'd have thought installer maybe. But to avoid ping pong I'll just assume you have a good reason for it to be all of sink. Link to CI run will be in the linked issue description.

2024-05-28 01:08 UTC, GuySartorelli commented on src/Context/LoginContext.php
> +        Member::set_password_validator($nullValidator);
Without this change, we get this error:
> You've already used that password in the past, please choose a new password

The comment makes it clear this was the intention here.
Outside of testing I can't see any reason to _not_ have a member password validator, and the current behaviour is when `null` is passed in the result is the default password validator is instantiated which IMO is good behaviour.

2024-05-28 01:09 UTC, GuySartorelli commented on src/Context/LoginContext.php
> -        $member->PasswordEncryption = "none";
This is the main change for this PR - anything else is done to support this change.

2024-05-28 21:27 UTC, emteknetnz approved these changes

2024-05-28 21:28 UTC, merged